<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LM-SJC-11013407" name="Command line test" tests="3" failures="1" timestamp="20 Oct 2018 21:40:09 GMT" time="0.473" errors="0">
  <testcase name="failTest" time="0.007" classname="com.xero.test.XeroTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.xero.test.XeroTests.failTest(XeroTests.java:77)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase name="passTest" time="0.0" classname="com.xero.test.XeroTests"/>
  <testcase name="skipTest" time="0.0" classname="com.xero.test.XeroTests">
    <skipped/>
  </testcase> <!-- skipTest -->
</testsuite> <!-- Command line test -->
